export const TIMER_CONFIG = {
  dsa: {
    easy: 20 * 60,
    medium: 35 * 60,
    hard: 45 * 60,
  },
  hld: {
    default: 45 * 60,
  },
  lld: {
    default: 60 * 60,
  },
} as const;

export const HLD_PROMPTS = [
  // --- EASY ---
  {
    id: "url-shortener",
    title: "Design a URL Shortener",
    prompt: "Design a URL shortening service like bit.ly or TinyURL that can handle 10M daily active users.",
    requirements: [
      "Handle 100K requests per second",
      "Short URLs should be unique and non-guessable",
      "Redirects should happen in < 100ms",
      "Support custom short URLs",
      "Track analytics (click count, geolocation)",
    ],
    difficulty: "easy" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/bitly",
    referenceLabel: "Hello Interview",
  },
  {
    id: "dropbox",
    title: "Design a File Storage Service (Dropbox)",
    prompt: "Design a cloud-based file storage service like Dropbox that allows users to store, sync, and share files across devices.",
    requirements: [
      "Users can upload and download files from any device",
      "Users can share files with other users",
      "Files sync automatically across all user devices",
      "Support files as large as 50GB",
      "Highly available with strong durability guarantees",
    ],
    difficulty: "easy" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/dropbox",
    referenceLabel: "Hello Interview",
  },
  // --- MEDIUM ---
  {
    id: "notification-system",
    title: "Design a Notification System",
    prompt: "Design a real-time notification system for a social media platform.",
    requirements: [
      "Send notifications to 100M users",
      "Real-time delivery (< 1 second latency)",
      "Support multiple notification types (likes, comments, messages)",
      "Users can subscribe to notification channels",
      "Guarantee at-least-once delivery",
    ],
    difficulty: "medium" as const,
  },
  {
    id: "cache-system",
    title: "Design a Distributed Cache",
    prompt: "Design a distributed caching system similar to Redis or Memcached.",
    requirements: [
      "Key-value store with expiration",
      "Distributed across multiple nodes",
      "Support LRU eviction",
      "Consistent hashing for scaling",
      "Handle node failures",
    ],
    difficulty: "medium" as const,
  },
  {
    id: "chat-system",
    title: "Design a Chat Application",
    prompt: "Design a real-time chat system supporting 10M concurrent users.",
    requirements: [
      "One-to-one and group messaging",
      "Real-time message delivery",
      "Message history and search",
      "User presence (online/offline status)",
      "Typing indicators",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/whatsapp",
    referenceLabel: "Hello Interview",
  },
  {
    id: "ticketmaster",
    title: "Design a Ticket Booking System (Ticketmaster)",
    prompt: "Design an online ticket booking platform like Ticketmaster supporting 10M users and high-traffic event launches.",
    requirements: [
      "Users can view and search for events",
      "Users can book tickets to events",
      "Prevent double-booking with strong consistency",
      "Handle high throughput for popular events (10M users, one event)",
      "Support seat selection and reservation hold",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/ticketmaster",
    referenceLabel: "Hello Interview",
  },
  // --- HARD ---
  {
    id: "search-engine",
    title: "Design a Search Engine",
    prompt: "Design a search engine that indexes and searches across billions of documents.",
    requirements: [
      "Index billions of web pages",
      "Return results in < 500ms",
      "Support full-text search with relevance ranking",
      "Handle misspellings and synonyms",
      "Distributed crawling and indexing",
    ],
    difficulty: "hard" as const,
  },
  {
    id: "video-platform",
    title: "Design a Video Streaming Platform",
    prompt: "Design a platform like YouTube that streams videos to millions of users.",
    requirements: [
      "Upload and transcode videos",
      "Stream to 10M concurrent users",
      "Support adaptive bitrate streaming",
      "CDN for global distribution",
      "Minimize startup time (< 2 seconds)",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/youtube",
    referenceLabel: "Hello Interview",
  },
  {
    id: "payment-system",
    title: "Design a Payment System",
    prompt: "Design a payment processing system for an e-commerce platform.",
    requirements: [
      "Handle transactions with strong consistency",
      "Support multiple payment methods",
      "Fraud detection and prevention",
      "High throughput (10K transactions/sec)",
      "Audit trail and dispute resolution",
    ],
    difficulty: "hard" as const,
  },
  {
    id: "recommendations",
    title: "Design a Recommendation System",
    prompt: "Design a recommendation engine for Netflix or Amazon.",
    requirements: [
      "Real-time personalization",
      "Handle cold-start problem for new users",
      "Support collaborative filtering",
      "A/B testing infrastructure",
      "Model serving at scale",
    ],
    difficulty: "hard" as const,
  },
  {
    id: "uber",
    title: "Design a Ride-Sharing App (Uber)",
    prompt: "Design a ride-sharing platform like Uber supporting 10M daily active users with real-time driver matching.",
    requirements: [
      "Riders can get fare estimates for a start/destination",
      "Riders can request a ride and be matched with a nearby driver in < 1 minute",
      "Drivers can accept/decline requests and navigate to pickup/drop-off",
      "Strong consistency in ride matching (no driver assigned to two rides)",
      "Handle frequent driver location updates at scale",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/uber",
    referenceLabel: "Hello Interview",
  },
  {
    id: "web-crawler",
    title: "Design a Web Crawler",
    prompt: "Design a distributed web crawler that can index 10 billion pages within 5 days.",
    requirements: [
      "Crawl the web starting from a set of seed URLs",
      "Extract and store text content from each page",
      "Fault-tolerant: resume crawling without losing progress on failure",
      "Polite crawling: respect robots.txt and avoid overloading servers",
      "Detect and avoid crawling duplicate content",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/web-crawler",
    referenceLabel: "Hello Interview",
  },
  {
    id: "ad-click-aggregator",
    title: "Design an Ad Click Aggregator",
    prompt: "Design a system that tracks ad clicks and provides real-time analytics to advertisers.",
    requirements: [
      "Users click on ads and are redirected to the advertiser's website",
      "Advertisers can query click metrics with 1-minute granularity",
      "Handle up to 10K clicks per second at peak",
      "Sub-second analytics query response time",
      "Prevent abuse from users clicking ads multiple times",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/ad-click-aggregator",
    referenceLabel: "Hello Interview",
  },
  {
    id: "top-k-videos",
    title: "Design YouTube Top-K Videos",
    prompt: "Design a system that tracks video view counts and serves top-K queries across different time windows.",
    requirements: [
      "Clients query top K videos (up to 1000 results)",
      "Support tumbling windows: 1 hour, 1 day, 1 month, and all-time",
      "At most 1 minute delay between a view event and tabulation",
      "Precise counts (no approximation allowed)",
      "Handle YouTube-scale write throughput",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/top-k",
    referenceLabel: "Hello Interview",
  },
  {
    id: "tinder",
    title: "Design a Dating App (Tinder)",
    prompt: "Design a matchmaking and swiping platform like Tinder for 20M daily active users.",
    requirements: [
      "Users create profiles with preferences (age range, interests, max distance)",
      "Users see a personalized stack of nearby profiles matching their preferences",
      "Users swipe right (yes) or left (no) on profiles",
      "A mutual right swipe triggers a match notification instantly",
      "Scale to 20M DAU with ~100 swipes per user per day",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/tinder",
    referenceLabel: "Hello Interview",
  },
];

export const LLD_PROMPTS = [
  // --- EASY ---
  {
    id: "snake-and-ladder",
    title: "Design Snake and Ladder Game",
    prompt: "Design an object-oriented system for a multiplayer Snake and Ladder game.",
    requirements: [
      "Board size is configurable (e.g., 100 squares)",
      "Multiple players can join a game",
      "Players roll a 6-sided die to move",
      "Snakes move players down, ladders move players up",
      "First player to reach the final square wins",
    ],
    difficulty: "easy" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/snake-and-ladder-problem-zgtac9lxwntg",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "tic-tac-toe",
    title: "Design Tic-Tac-Toe Game",
    prompt: "Design an object-oriented system for a two-player Tic-Tac-Toe game with a command-line interface.",
    requirements: [
      "Two players alternate placing X and O on a 3x3 grid",
      "Validate moves: only empty cells, correct player's turn",
      "Detect win condition (horizontal, vertical, diagonal) and draw",
      "Print the board state after every valid move",
      "Handle invalid moves gracefully with appropriate messages",
    ],
    difficulty: "easy" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-tic-tac-toe-smyfi9x064ry",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "2048-game",
    title: "Design 2048 Game",
    prompt: "Design an object-oriented system for the 2048 sliding tile game with a command-line interface.",
    requirements: [
      "Initialize a 4x4 grid with two tiles numbered 2 at random positions",
      "Players move tiles in 4 directions (up, down, left, right)",
      "Adjacent tiles with equal numbers merge into their sum",
      "Add a new tile (2 or 4) after each valid move",
      "Detect win (tile reaches 2048) and lose (no valid moves left)",
    ],
    difficulty: "easy" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-2048-game-osycd22zpn1y",
    referenceLabel: "WorkAt Tech",
  },
  // --- MEDIUM ---
  {
    id: "parking-lot",
    title: "Design a Parking Lot",
    prompt: "Design an object-oriented system for a multi-level parking lot.",
    requirements: [
      "Support multiple vehicle types (car, truck, motorcycle)",
      "Support multiple parking spot types (compact, large, handicapped)",
      "Issue a parking ticket at the entrance",
      "Calculate payment at the exit based on vehicle type and duration",
      "Track capacity and full status for each level",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-parking-lot-qm6hwq4wkhp8",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "splitwise",
    title: "Design Expense Sharing App (Splitwise)",
    prompt: "Design an object-oriented expense-sharing application where users can add expenses and split them among groups.",
    requirements: [
      "Users add expenses and split by EQUAL, EXACT amount, or PERCENT",
      "Track balances between all users (who owes how much to whom)",
      "Validate percent splits sum to 100% and exact splits sum to total",
      "Show all balances or balances for a specific user",
      "Round amounts to 2 decimal places consistently",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/splitwise-problem-0kp2yneec2q2",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "chess-validator",
    title: "Design a Chess Validator",
    prompt: "Design an object-oriented chess validator that enforces rules and tracks game state.",
    requirements: [
      "Initialize a chessboard with all pieces in correct starting positions",
      "Validate moves for each piece type (pawn, rook, bishop, knight, queen, king)",
      "Two players alternate turns; detect and reject invalid moves",
      "Detect check and checkmate conditions",
      "Display the board state after every valid move",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-chess-validator-to77d8oqpx2h",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "library-management",
    title: "Design a Library Management System",
    prompt: "Design an object-oriented system for a local library.",
    requirements: [
      "Search catalog by title, author, subject, or publication date",
      "Users can borrow, return, and reserve books",
      "Calculate fines for overdue books",
      "Support different user types (member, librarian)",
      "Send notifications for reservations and due dates",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-library-management-system-jgjrv8q8b136",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "trello",
    title: "Design Project Management Tool (Trello)",
    prompt: "Design an object-oriented project management system like Trello with boards, lists, and cards.",
    requirements: [
      "Create/delete boards with members, privacy settings (public/private), and auto-generated URLs",
      "Create/delete lists within boards; deleting a board cascades to its lists",
      "Create/delete cards within lists; assign/unassign members to cards",
      "Move cards across lists within the same board",
      "Show all boards, a single board, a single list, or a single card",
    ],
    difficulty: "medium" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/trello-problem-t0nwwqt61buz",
    referenceLabel: "WorkAt Tech",
  },
  // --- HARD ---
  {
    id: "key-value-store",
    title: "Design an In-Memory Key-Value Store (Redis-like)",
    prompt: "Design a thread-safe, in-memory key-value store similar to Redis supporting structured attribute values.",
    requirements: [
      "Thread-safe get, put, delete, keys, and search operations",
      "Keys are strings; values are objects with named attributes (string, int, double, boolean)",
      "Search returns all keys matching a given attribute key-value pair",
      "Attribute types are fixed on first insertion; type mismatch throws an exception",
      "put replaces existing value; delete removes the key entirely",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-key-value-store-6gz6cq124k65",
    referenceLabel: "WorkAt Tech",
  },
  {
    id: "distributed-queue",
    title: "Design a Distributed Queue (Kafka-like)",
    prompt: "Design an in-memory distributed message queue system like Apache Kafka with topics, producers, and consumers.",
    requirements: [
      "Support multiple topics; producers publish string messages to topics",
      "Multiple consumers can subscribe to multiple topics",
      "Messages are delivered to all subscribers of a topic",
      "System is multi-threaded: messages can be produced and consumed in parallel",
      "Consumer prints '<consumer_id> received <message>' on receiving a message",
    ],
    difficulty: "hard" as const,
    referenceUrl: "https://workat.tech/machine-coding/practice/design-distributed-queue-cuudq0sk0v14",
    referenceLabel: "WorkAt Tech",
  },
];
