"use client";

import { useEffect, useRef, forwardRef, useImperativeHandle } from "react";
import { Excalidraw, MainMenu, DefaultSidebar } from "@excalidraw/excalidraw";
import "@excalidraw/excalidraw/index.css";
import type { ExcalidrawAPI, ExcalidrawInitialDataState } from "@excalidraw/excalidraw/types";

const architectureElements: ExcalidrawInitialDataState["elements"] = [
  {
    id: "client",
    type: "rectangle",
    x: 50,
    y: 50,
    width: 80,
    height: 50,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "#1e1e2e",
    fillStyle: "solid",
    strokeWidth: 2,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    seed: 1,
    versionNonce: 1,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "client-text",
    type: "text",
    x: 50,
    y: 70,
    width: 80,
    height: 20,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    text: "Client",
    fontSize: 14,
    fontFamily: 2,
    textAlign: "center",
    verticalAlign: "middle",
    containerId: "client",
    originalText: "Client",
    lineHeight: 1.5,
    seed: 2,
    versionNonce: 2,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "cdn",
    type: "rectangle",
    x: 200,
    y: 50,
    width: 80,
    height: 50,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "#1e1e2e",
    fillStyle: "solid",
    strokeWidth: 2,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    seed: 3,
    versionNonce: 3,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "cdn-text",
    type: "text",
    x: 200,
    y: 70,
    width: 80,
    height: 20,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    text: "CDN",
    fontSize: 14,
    fontFamily: 2,
    textAlign: "center",
    verticalAlign: "middle",
    containerId: "cdn",
    originalText: "CDN",
    lineHeight: 1.5,
    seed: 4,
    versionNonce: 4,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "lb",
    type: "rectangle",
    x: 350,
    y: 50,
    width: 80,
    height: 50,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "#1e1e2e",
    fillStyle: "solid",
    strokeWidth: 2,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    seed: 5,
    versionNonce: 5,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "lb-text",
    type: "text",
    x: 350,
    y: 70,
    width: 80,
    height: 20,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    text: "Load Balancer",
    fontSize: 12,
    fontFamily: 2,
    textAlign: "center",
    verticalAlign: "middle",
    containerId: "lb",
    originalText: "Load Balancer",
    lineHeight: 1.5,
    seed: 6,
    versionNonce: 6,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "app1",
    type: "rectangle",
    x: 200,
    y: 180,
    width: 80,
    height: 50,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "#1e1e2e",
    fillStyle: "solid",
    strokeWidth: 2,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    seed: 7,
    versionNonce: 7,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "app1-text",
    type: "text",
    x: 200,
    y: 200,
    width: 80,
    height: 20,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    text: "App Server 1",
    fontSize: 12,
    fontFamily: 2,
    textAlign: "center",
    verticalAlign: "middle",
    containerId: "app1",
    originalText: "App Server 1",
    lineHeight: 1.5,
    seed: 8,
    versionNonce: 8,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "app2",
    type: "rectangle",
    x: 350,
    y: 180,
    width: 80,
    height: 50,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "#1e1e2e",
    fillStyle: "solid",
    strokeWidth: 2,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    seed: 9,
    versionNonce: 9,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "app2-text",
    type: "text",
    x: 350,
    y: 200,
    width: 80,
    height: 20,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    text: "App Server 2",
    fontSize: 12,
    fontFamily: 2,
    textAlign: "center",
    verticalAlign: "middle",
    containerId: "app2",
    originalText: "App Server 2",
    lineHeight: 1.5,
    seed: 10,
    versionNonce: 10,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "db",
    type: "rectangle",
    x: 200,
    y: 310,
    width: 80,
    height: 50,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "#1e1e2e",
    fillStyle: "solid",
    strokeWidth: 2,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    seed: 11,
    versionNonce: 11,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "db-text",
    type: "text",
    x: 200,
    y: 330,
    width: 80,
    height: 20,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    text: "Primary DB",
    fontSize: 12,
    fontFamily: 2,
    textAlign: "center",
    verticalAlign: "middle",
    containerId: "db",
    originalText: "Primary DB",
    lineHeight: 1.5,
    seed: 12,
    versionNonce: 12,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "cache",
    type: "rectangle",
    x: 350,
    y: 310,
    width: 80,
    height: 50,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "#1e1e2e",
    fillStyle: "solid",
    strokeWidth: 2,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    seed: 13,
    versionNonce: 13,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
  {
    id: "cache-text",
    type: "text",
    x: 350,
    y: 330,
    width: 80,
    height: 20,
    angle: 0,
    strokeColor: "#6366f1",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1,
    strokeStyle: "solid",
    roughness: 0,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    text: "Cache (Redis)",
    fontSize: 12,
    fontFamily: 2,
    textAlign: "center",
    verticalAlign: "middle",
    containerId: "cache",
    originalText: "Cache (Redis)",
    lineHeight: 1.5,
    seed: 14,
    versionNonce: 14,
    isDeleted: false,
    boundElements: null,
    updated: 1,
    link: null,
    locked: false,
  } as any,
];

interface ExcalidrawCanvasHandle {
  getDescription: () => string;
}

export const ExcalidrawCanvas = forwardRef<ExcalidrawCanvasHandle>((_, ref) => {
  const excalidrawAPI = useRef<ExcalidrawAPI>(null);

  useImperativeHandle(ref, () => ({
    getDescription: () => {
      if (!excalidrawAPI.current) return "";
      const elements = excalidrawAPI.current.getSceneElements();
      const textLabels = elements
        .filter((el: any) => el.type === "text" && el.text)
        .map((el: any) => el.text);
      const arrows = elements.filter((el: any) => el.type === "arrow");
      return `Architecture components: ${textLabels.join(", ")}. Connections: ${arrows.length} arrows. Total custom elements: ${elements.filter((el: any) => !["client", "cdn", "lb", "app1", "app2", "db", "cache"].includes(el.id)).length}`;
    },
  }));

  return (
    <div className="w-full h-full bg-slate-900 rounded-lg overflow-hidden border border-slate-800">
      <Excalidraw
        ref={excalidrawAPI}
        initialData={{
          elements: architectureElements,
        }}
        UIOptions={{
          canvasMenu: { defaultItems: [] },
          tools: {
            image: false,
          },
        }}
        viewBackgroundColor="#0F0F0F"
        theme="dark"
      />
    </div>
  );
});

ExcalidrawCanvas.displayName = "ExcalidrawCanvas";
